### PR TITLE
Uses loadConfig from tsconfig-paths to load tsconfig.json

### PR DESCRIPTION
**Pull request by highflying**
The current implementation doesn't support the `extends` option in a `tsconfig.json` file. This PR uses `tsconfig-paths`' `loadConfig` method to read in the file.

### CODE REVIEW

**Comment by FDiskas** [comment]
Project probably not maintained any more

**Comment by sebastianmusial** [comment]
@FDiskas @highflying Sorry, new version will be available in the next days.

**Comment by sebastianmusial** [comment]
@highflying Can I ask you to resolve conflicts?

**Comment by FDiskas** [comment]
Actually yarn.lock is not the case to solve conflicts. :/ the idea to good to be dropped or unresponsive.

**Comment by FabianMeul** [comment]
@FDiskas Fix the conflicts, so this can get merged. 

It's is a nice addition :-)

**Comment by FDiskas** [comment]
@FabianMeul  
> Only those with write access to this repository can merge pull requests.

**Comment by FabianMeul** [comment]
> @FabianMeul
> 
> > Only those with write access to this repository can merge pull requests.

Oh damn, I meant @highflying , of course :-D

**Pull request closed without merging**
